# Generated by Django 4.2 on 2023-05-01 15:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0004_remove_list_is_done_remove_list_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='at_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
