# Generated by Django 4.2 on 2023-05-01 15:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0006_alter_task_at_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='desc',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='task',
            name='at_time',
            field=models.TimeField(default=datetime.datetime(2023, 5, 1, 18, 54, 54, 459903)),
        ),
        migrations.AlterField(
            model_name='task',
            name='desc',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
    ]
