# Generated by Django 4.2 on 2023-05-16 20:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0008_alter_task_options_alter_task_at_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='at_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
