# Generated by Django 4.2 on 2023-05-16 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0009_alter_task_at_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='at_time',
            field=models.TimeField(default=(2023, 5, 16, 23, 9, 24, 1, 136, 1)),
        ),
    ]
