# Generated by Django 4.2 on 2023-05-16 20:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0010_alter_task_at_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='at_time',
            field=models.TimeField(default=datetime.time(23, 10, 31, 41903)),
        ),
    ]
