# Generated by Django 4.2 on 2023-05-16 21:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0012_alter_task_at_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='at_time',
            field=models.TimeField(default=datetime.time(21, 6, 41, 454585)),
        ),
    ]
