version: '3'

services:
  django2:
    build: .
    container_name: django2
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - .:/usr/srs/app
    ports:
      - 8080:8080
    depends_on:
      - db2
  db2:
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      - ./db/:/root/db/
    container_name: db2
